apiVersion: v1
kind: Secret
metadata:
  name: {{ include "..fullname" . }}-auth
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  ADMINUSER: {{ .Values.ldap.ADMINUSER | b64enc }}
  ADMINPASS: {{ .Values.ldap.ADMINPASS | b64enc }}
  DMUSER: {{ .Values.ldap.DMUSER | b64enc }}
  DMPASS: {{ .Values.ldap.DMPASS | b64enc }}
